version: "2.1"
services:
  thumbor:
    image: apsl/thumbor
    environment:
    - UPLOAD_ENABLED=True
    - UPLOAD_PUT_ALLOWED=True
    - UPLOAD_DELETE_ALLOWED=true
    healthcheck:
      test: [ "CMD", "curl", "localhost:8000/healthcheck" ]
  unitest-nodejs:
    build: .
    links:
    - thumbor
    environment:
    - thumbor=thumbor:8000
    volumes:
    - "/opt/app/node_modules"
    - "./:/opt/app/"
    depends_on:
      thumbor:
        condition: service_healthy
    command: [ "yarn", "run", "nodemon", "--ext", "js", "--ignore", "node_modules", "--exec", "yarn run jasmine" ]

